
version: 2

models:
  - name: aggregate-transactions
    description: "Aggregate daily transactions"

  - name: addresses_by_day
    description: "Aggreagate daily contract and wallet addresses"
    columns:
