version: 2

models:
  - name: aggregate_transactions
    description: "Aggregate daily transactions"

  - name: aggregate_addresses_by_day
    description: "Aggreagate daily contract and wallet addresses"
  
  - name: aggregate_celo_wallets_by_day
    description: "Aggreagate daily celo wallet counts"
  
  - name: aggregate_active_addresses_by_day
    description: "Aggreagate active contract/wallet addresses by day (at least 1 transaction in the last 30 days)"